// <auto-generated />
using System;
using BeaconApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BeaconApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BeaconApi.Data.Models.Beacon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("mac");

                    b.HasKey("id");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("BeaconApi.Data.Models.Container", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("containerName");

                    b.HasKey("id");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("BeaconApi.Data.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("containerId");

                    b.Property<DateTime>("created_on");

                    b.Property<string>("password");

                    b.Property<string>("token");

                    b.Property<DateTime>("token_created_on");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.HasIndex("containerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeaconApi.Data.Models.UserBeacon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("beaconId");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.HasIndex("beaconId");

                    b.HasIndex("userId");

                    b.ToTable("UserBeacons");
                });

            modelBuilder.Entity("BeaconApi.Data.Models.User", b =>
                {
                    b.HasOne("BeaconApi.Data.Models.Container", "container")
                        .WithMany()
                        .HasForeignKey("containerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeaconApi.Data.Models.UserBeacon", b =>
                {
                    b.HasOne("BeaconApi.Data.Models.Beacon", "beacon")
                        .WithMany()
                        .HasForeignKey("beaconId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeaconApi.Data.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
